### ISSUE TITLE
怎么解决啊[MainThread]load last result,ok cnt:51780,ok file line:319,error cnt: 22517116

### ISSUE THREAD

**Issue by lsnmx** [moonshawdo/checkgoogleip#42]
@YKG 停止扫描后，重新打开就这样，麻烦了
D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local>"D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\python27.exe" "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py"
[MainThread]load last result,ok cnt:51780,ok file line:319,error cnt: 22517116
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py", line 1064, in <module>
    list_ping()
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\goagent_gvs\local\checkip.py", line 994, in list_ping
    ramdomip_thread = RamdomIP(checkqueue,cacheResult,lastokresult|lasterrorresult)
MemoryError

**Comment by lsnmx** [comment]
@gulucn 停止扫描后，重新打开就这样，麻烦了

**Comment by lsnmx** [comment]
@moonshawdo 停止扫描后，重新打开就这样，麻烦了
