### ISSUE TITLE
如何解决ValueError: invalid literal for int() with base 10: 

### ISSUE THREAD

**Issue by lsnmx** [moonshawdo/checkgoogleip#47]
谢谢

@gulucn @YKG @moonshawdo 

Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1101, in <module>
    main()
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 1084, in main
    list_ping(g_googleipfile)
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 989, in list_ping
    lastokresult,lasterrorresult = cacheResult.loadLastResult()
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 405, in loadLastResult
    errorresult.add(from_string(item))
  File "D:\Program Files (x86)\Goagent X\CheckGoogleIP\CheckIpTools_GVS\python/checkip.py", line 843, in from_string
    return reduce(lambda a, b: a << 8 | b, map(int, s.split(".")))
ValueError: invalid literal for int() with base 10: ''

**Comment by YKG** [comment]
错误提示是是说想把一个字符串转换成int时出错了，错误原因是该字符串是`''`，是一个空串。
所以有可能你的`ip_tmperror.txt`这个文件里面数据格式有问题。你可以检查下这个文件的格式看看问题在哪里，如果单纯想跳过可能的错误，我估计把这个文件内容清空应该就可以解决吧。
